/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthenticatedAssessmentRouteImport } from './routes/_authenticated/assessment'
import { Route as AuthenticatedCoursesRouteImport } from './routes/_authenticated/courses'
import { Route as AuthenticatedCurriculumRouteImport } from './routes/_authenticated/curriculum'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDistrictPlannerRouteImport } from './routes/_authenticated/district-planner'
import { Route as AuthenticatedEmployerValidationRouteImport } from './routes/_authenticated/employer-validation'
import { Route as AuthenticatedLearningPathRouteImport } from './routes/_authenticated/learning-path'
import { Route as AuthenticatedMySkillsRouteImport } from './routes/_authenticated/my-skills'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSkillGapRouteImport } from './routes/_authenticated/skill-gap'
import { Route as AuthenticatedTrainingCapacityRouteImport } from './routes/_authenticated/training-capacity'
import { Route as AuthenticatedIndustryDemandIndexRouteImport } from './routes/_authenticated/industry-demand/index'
import { Route as AuthenticatedIndustryDemandEmergingRouteImport } from './routes/_authenticated/industry-demand/emerging'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthenticatedAssessmentRoute = AuthenticatedAssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoursesRoute = AuthenticatedCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCurriculumRoute = AuthenticatedCurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDistrictPlannerRoute =
  AuthenticatedDistrictPlannerRouteImport.update({
    id: '/district-planner',
    path: '/district-planner',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerValidationRoute =
  AuthenticatedEmployerValidationRouteImport.update({
    id: '/employer-validation',
    path: '/employer-validation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLearningPathRoute =
  AuthenticatedLearningPathRouteImport.update({
    id: '/learning-path',
    path: '/learning-path',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMySkillsRoute = AuthenticatedMySkillsRouteImport.update({
  id: '/my-skills',
  path: '/my-skills',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSkillGapRoute = AuthenticatedSkillGapRouteImport.update({
  id: '/skill-gap',
  path: '/skill-gap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrainingCapacityRoute =
  AuthenticatedTrainingCapacityRouteImport.update({
    id: '/training-capacity',
    path: '/training-capacity',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIndustryDemandIndexRoute =
  AuthenticatedIndustryDemandIndexRouteImport.update({
    id: '/industry-demand/',
    path: '/industry-demand/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIndustryDemandEmergingRoute =
  AuthenticatedIndustryDemandEmergingRouteImport.update({
    id: '/industry-demand/emerging',
    path: '/industry-demand/emerging',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/assessment': typeof AuthenticatedAssessmentRoute
  '/courses': typeof AuthenticatedCoursesRoute
  '/curriculum': typeof AuthenticatedCurriculumRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/district-planner': typeof AuthenticatedDistrictPlannerRoute
  '/employer-validation': typeof AuthenticatedEmployerValidationRoute
  '/learning-path': typeof AuthenticatedLearningPathRoute
  '/my-skills': typeof AuthenticatedMySkillsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/skill-gap': typeof AuthenticatedSkillGapRoute
  '/training-capacity': typeof AuthenticatedTrainingCapacityRoute
  '/industry-demand/emerging': typeof AuthenticatedIndustryDemandEmergingRoute
  '/industry-demand/': typeof AuthenticatedIndustryDemandIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/assessment': typeof AuthenticatedAssessmentRoute
  '/courses': typeof AuthenticatedCoursesRoute
  '/curriculum': typeof AuthenticatedCurriculumRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/district-planner': typeof AuthenticatedDistrictPlannerRoute
  '/employer-validation': typeof AuthenticatedEmployerValidationRoute
  '/learning-path': typeof AuthenticatedLearningPathRoute
  '/my-skills': typeof AuthenticatedMySkillsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/skill-gap': typeof AuthenticatedSkillGapRoute
  '/training-capacity': typeof AuthenticatedTrainingCapacityRoute
  '/industry-demand/emerging': typeof AuthenticatedIndustryDemandEmergingRoute
  '/industry-demand': typeof AuthenticatedIndustryDemandIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_authenticated/assessment': typeof AuthenticatedAssessmentRoute
  '/_authenticated/courses': typeof AuthenticatedCoursesRoute
  '/_authenticated/curriculum': typeof AuthenticatedCurriculumRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/district-planner': typeof AuthenticatedDistrictPlannerRoute
  '/_authenticated/employer-validation': typeof AuthenticatedEmployerValidationRoute
  '/_authenticated/learning-path': typeof AuthenticatedLearningPathRoute
  '/_authenticated/my-skills': typeof AuthenticatedMySkillsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/skill-gap': typeof AuthenticatedSkillGapRoute
  '/_authenticated/training-capacity': typeof AuthenticatedTrainingCapacityRoute
  '/_authenticated/industry-demand/emerging': typeof AuthenticatedIndustryDemandEmergingRoute
  '/_authenticated/industry-demand/': typeof AuthenticatedIndustryDemandIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/assessment'
    | '/courses'
    | '/curriculum'
    | '/dashboard'
    | '/district-planner'
    | '/employer-validation'
    | '/learning-path'
    | '/my-skills'
    | '/profile'
    | '/settings'
    | '/skill-gap'
    | '/training-capacity'
    | '/industry-demand/emerging'
    | '/industry-demand/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/assessment'
    | '/courses'
    | '/curriculum'
    | '/dashboard'
    | '/district-planner'
    | '/employer-validation'
    | '/learning-path'
    | '/my-skills'
    | '/profile'
    | '/settings'
    | '/skill-gap'
    | '/training-capacity'
    | '/industry-demand/emerging'
    | '/industry-demand'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_authenticated'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_authenticated/assessment'
    | '/_authenticated/courses'
    | '/_authenticated/curriculum'
    | '/_authenticated/dashboard'
    | '/_authenticated/district-planner'
    | '/_authenticated/employer-validation'
    | '/_authenticated/learning-path'
    | '/_authenticated/my-skills'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/skill-gap'
    | '/_authenticated/training-capacity'
    | '/_authenticated/industry-demand/emerging'
    | '/_authenticated/industry-demand/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authenticated/assessment': {
      id: '/_authenticated/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AuthenticatedAssessmentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses': {
      id: '/_authenticated/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AuthenticatedCoursesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/curriculum': {
      id: '/_authenticated/curriculum'
      path: '/curriculum'
      fullPath: '/curriculum'
      preLoaderRoute: typeof AuthenticatedCurriculumRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/district-planner': {
      id: '/_authenticated/district-planner'
      path: '/district-planner'
      fullPath: '/district-planner'
      preLoaderRoute: typeof AuthenticatedDistrictPlannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer-validation': {
      id: '/_authenticated/employer-validation'
      path: '/employer-validation'
      fullPath: '/employer-validation'
      preLoaderRoute: typeof AuthenticatedEmployerValidationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learning-path': {
      id: '/_authenticated/learning-path'
      path: '/learning-path'
      fullPath: '/learning-path'
      preLoaderRoute: typeof AuthenticatedLearningPathRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-skills': {
      id: '/_authenticated/my-skills'
      path: '/my-skills'
      fullPath: '/my-skills'
      preLoaderRoute: typeof AuthenticatedMySkillsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/skill-gap': {
      id: '/_authenticated/skill-gap'
      path: '/skill-gap'
      fullPath: '/skill-gap'
      preLoaderRoute: typeof AuthenticatedSkillGapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/training-capacity': {
      id: '/_authenticated/training-capacity'
      path: '/training-capacity'
      fullPath: '/training-capacity'
      preLoaderRoute: typeof AuthenticatedTrainingCapacityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/industry-demand/': {
      id: '/_authenticated/industry-demand/'
      path: '/industry-demand'
      fullPath: '/industry-demand/'
      preLoaderRoute: typeof AuthenticatedIndustryDemandIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/industry-demand/emerging': {
      id: '/_authenticated/industry-demand/emerging'
      path: '/industry-demand/emerging'
      fullPath: '/industry-demand/emerging'
      preLoaderRoute: typeof AuthenticatedIndustryDemandEmergingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssessmentRoute: typeof AuthenticatedAssessmentRoute
  AuthenticatedCoursesRoute: typeof AuthenticatedCoursesRoute
  AuthenticatedCurriculumRoute: typeof AuthenticatedCurriculumRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDistrictPlannerRoute: typeof AuthenticatedDistrictPlannerRoute
  AuthenticatedEmployerValidationRoute: typeof AuthenticatedEmployerValidationRoute
  AuthenticatedLearningPathRoute: typeof AuthenticatedLearningPathRoute
  AuthenticatedMySkillsRoute: typeof AuthenticatedMySkillsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSkillGapRoute: typeof AuthenticatedSkillGapRoute
  AuthenticatedTrainingCapacityRoute: typeof AuthenticatedTrainingCapacityRoute
  AuthenticatedIndustryDemandEmergingRoute: typeof AuthenticatedIndustryDemandEmergingRoute
  AuthenticatedIndustryDemandIndexRoute: typeof AuthenticatedIndustryDemandIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssessmentRoute: AuthenticatedAssessmentRoute,
  AuthenticatedCoursesRoute: AuthenticatedCoursesRoute,
  AuthenticatedCurriculumRoute: AuthenticatedCurriculumRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDistrictPlannerRoute: AuthenticatedDistrictPlannerRoute,
  AuthenticatedEmployerValidationRoute: AuthenticatedEmployerValidationRoute,
  AuthenticatedLearningPathRoute: AuthenticatedLearningPathRoute,
  AuthenticatedMySkillsRoute: AuthenticatedMySkillsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSkillGapRoute: AuthenticatedSkillGapRoute,
  AuthenticatedTrainingCapacityRoute: AuthenticatedTrainingCapacityRoute,
  AuthenticatedIndustryDemandEmergingRoute:
    AuthenticatedIndustryDemandEmergingRoute,
  AuthenticatedIndustryDemandIndexRoute: AuthenticatedIndustryDemandIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
